name: avalon_app
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  cached_network_image: ^3.2.1
  cupertino_icons: ^1.0.2
  dartz: ^0.10.1
  equatable: ^2.0.3
  flare_flutter:
    git:
      url: https://github.com/tsinis/Flare-Flutter
      path: flare_flutter/
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.1
  flutter_localizations:
    sdk: flutter
  flutter_svg: ^1.1.0
  get_it: ^7.2.0
  google_fonts: ^3.0.1
  hive: ^2.2.2
  http: ^0.13.4
  path_provider: ^2.0.11
  wiredash: ^0.7.1

dev_dependencies:
  bloc_test: ^9.0.3
  build_runner: ^2.1.11
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  hive_generator: ^1.1.3
  mockito: ^5.2.0
  flutter_launcher_icons: ^0.9.0

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/logo.png"

flutter:
  uses-material-design: true
  assets:
    - assets/svgs/
    - assets/pngs/
    - assets/languages/
    - assets/animations/
